WITH
    USERS_2021 AS (
        SELECT
            USER_ID,
            COUNT(*) OVER () AS COUNT_JOINED_2021
        FROM
            USER_INFO
        WHERE
            YEAR(JOINED)=2021
    )
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USERS_2021.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT USERS_2021.USER_ID)/MAX(COUNT_JOINED_2021),
        1
    ) AS PURCHASED_RATIO
FROM
    ONLINE_SALE
    LEFT OUTER JOIN USERS_2021 ON ONLINE_SALE.USER_ID=USERS_2021.USER_ID
GROUP BY
    YEAR,
    MONTH
ORDER BY
    YEAR,
    MONTH;