-- With subquery
SELECT
    COUNT(*) AS FISH_COUNT
FROM
    FISH_INFO
WHERE
    FISH_TYPE IN (
        SELECT
            FISH_TYPE
        FROM
            FISH_NAME_INFO
        WHERE
            FISH_NAME IN ('BASS', "SNAPPER")
    );

-- With join
SELECT
    COUNT(*) AS FISH_COUNT
FROM
    FISH_INFO
    INNER JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE=FISH_NAME_INFO.FISH_TYPE
WHERE
    FISH_NAME_INFO.FISH_NAME IN ('BASS', "SNAPPER");