-- With subquery
SELECT
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR
WHERE
    CAR_TYPE='세단'
    AND CAR_ID IN (
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            MONTH(START_DATE)=10
    )
ORDER BY
    CAR_ID DESC;

-- With JOIN
SELECT DISTINCT
    CARS.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR AS CARS
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CARS.CAR_ID=HISTORY.CAR_ID
WHERE
    CARS.CAR_TYPE='세단'
    AND MONTH(HISTORY.START_DATE)=10
ORDER BY
    CAR_ID DESC;