SELECT
    WRITER_ID,
    NICKNAME,
    SUM(PRICE)
FROM
    USED_GOODS_BOARD AS board
    INNER JOIN USED_GOODS_USER AS USER ON board.WRITER_ID=USER.USER_ID
WHERE
    STATUS='Done'
GROUP BY
    WRITER_ID
HAVING
    SUM(PRICE)>=700000
ORDER BY
    SUM(PRICE);