SELECT
    CAR_ID,
    CAR_TYPE,
    FLOOR(DAILY_FEE*30*(1-DISCOUNT_RATE/100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR
    NATURAL JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE
    CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE LIKE '30%'
    AND CAR_ID NOT IN(
        SELECT DISTINCT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            END_DATE>='2022-11-01'
            AND START_DATE<='2022-11-30'
    )
    AND (
        FLOOR(DAILY_FEE*30*(1-DISCOUNT_RATE/100)) BETWEEN 500000 AND 2000000
    )
ORDER BY
    FEE DESC,
    CAR_TYPE,
    CAR_ID DESC;