SELECT
    USER_ID,
    NICKNAME,
    CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS "전체주소",
    CONCAT_WS(
        "-",
        SUBSTRING(TLNO, 1, 3),
        SUBSTRING(TLNO, 4, 4),
        SUBSTRING(TLNO, 8, 4)
    ) AS "전화번호"
FROM
    USED_GOODS_BOARD AS BOARD
    INNER JOIN USED_GOODS_USER AS USER ON BOARD.WRITER_ID=USER.USER_ID
GROUP BY
    USER_ID
HAVING
    COUNT(*)>=3
ORDER BY
    USER_ID DESC;