SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT
    NATURAL JOIN FOOD_ORDER
WHERE
    PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID;