SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE*SALES) AS TOTAL_SALES
FROM
    BOOK
    NATURAL JOIN AUTHOR
    NATURAL JOIN BOOK_SALES
WHERE
    YEAR(SALES_DATE)=2022
    AND MONTH(SALES_DATE)=1
GROUP BY
    AUTHOR_ID,
    CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC;